py_project(
    name = "shoggoth",
    main = "src/python/shoggoth/repl/__main__.py",
    main_deps = [
        py_requirement("prompt_toolkit"),
        py_requirement("yaspin"),
    ],
    lib_deps = [
        py_requirement("lark"),
        py_requirement("flask"),
    ],
)
