py_project(
    name = "shogoth",
    main = "src/python/shogoth/repl/__main__.py",
    main_deps = [
        py_requirement("prompt_toolkit"),
        py_requirement("yaspin"),
    ],
    lib_deps = [
        py_requirement("lark"),
    ],
)
