# WARNING: YAMLLINT is GLP3'd code. Do not extend, modify or depend on this as a lib.
py_binary(
    name = "yamllint",
    main = "__main__.py",
    deps = [
        py_requirement("yamllint"),
    ],
    visibility = [
        "//visibility:public"
    ],
)
