zapp_binary(
    name = "cram",
    main = "src/python/cram/__main__.py",
    imports = [
        "src/python"
    ],
    deps = [
        "//projects/vfs",
        py_requirement("click"),
        py_requirement("toposort"),
    ]
)
