%import common.WORD
%import common.INT
%import common.FLOAT
%import common.WS
%ignore WS

STRING: /""".*?"""/ | /".*?"/

int: INT
float: FLOAT
number: int | float
word: WORD ("." WORD)*
string: STRING
atom: number | word | string

application: word "[" arguments? "]"

expr: application | atom

args: expr ("," args)?

kwargs: expr ":" expr ("," kwargs)?

a_args_kwargs: args ";" kwargs
a_args: args
a_kwargs: kwargs
arguments: a_args_kwargs | a_args | a_kwargs

header: "!" application
