py_binary(
    name = "updater",
    entry_point = "src/python/arrdem/updater/__main__.py",
    deps = [
        "//projects/gandi",
        py_requirement("jinja2"),
        py_requirement("pyyaml"),
    ]
)
