py_binary(
    name = "sphinx",
    main = "__main__.py",
    deps = [
        py_requirement("click"),
        py_requirement("recommonmark"),
        py_requirement("sphinx"),
        py_requirement("sphinxcontrib-openapi"),
        py_requirement("sphinxcontrib-programoutput"),
        py_requirement("livereload"),
    ]
)
