zapp_binary(
    name = "octostep",
    shebang = "/usr/bin/env /usr/bin/python3",
    main = "__main__.py",
    deps = [
        py_requirement("colored"),
        py_requirement("octorest"),
        py_requirement("pyyaml"),
    ],
)
