exports_files(["flake8.cfg"], visibility=["//visibility:public"])

py_binary(
    name = "flake8",
    main = "__main__.py",
    deps = [
        py_requirement("flake8"),
    ],
    visibility = [
        "//visibility:public"
    ],
)
