package(default_visibility = ["//visibility:public"])

py_library(
    name = "lib",
    srcs = glob(["src/**/*.py"]),
    imports = ["src"],
    deps = [
        py_requirement("pyrsistent"),
    ]
)
