py_binary(
    name = "datalog-shell",
    main = "src/python/datalog/shell/__main__.py",
    imports = [
        "src/python"
    ],
    deps = [
        "//projects/datalog",
        py_requirement("prompt_toolkit"),
        py_requirement("yaspin"),
    ]
)
