name: Bazel test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bazel test
      uses: ngalaiko/bazel-action@2.0.0
      with:
        args: ["test", "..."]
