zapp_binary(
    name = "hash_copy",
    main = "hash_copy.py",
    srcs = [
        "util.py"
    ],
)

zapp_binary(
    name = "org_photos",
    main = "org_photos.py",
    srcs = [
        "util.py"
    ],
    deps = [
        py_requirement("ExifRead"),
    ]
)
